### ISSUE TITLE
GT Mode user input/control over suggestions

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/APT#182]
Suggestions are auto-generated and totally inflexible right now I believe. User might want at least a little input. Consider cmdline api to give the user some access

**Comment by arobie** [comment]
I think adding gt suggestions list should be a GUI interface

**Comment by allenleetc** [comment]
Evaluate> import user GT table accepts fullpaths in the .mov column. However, they have to match rows of lObj.movieFilesAllFull. APT tries to standardize paths based on platform etc, but it can only be so smart. It will tell you if it fails.
