### ISSUE TITLE
Import trkfiles/preds during GT mode

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/APT#205]
Use case:
- compare 3rd party tracking to APT-generated tracking on GT movs
- compute APT-style GT performance on imported 3rd party tracking

Impl note, probably want to add labeledpos2GT etc.

**Comment by allenleetc** [comment]
re import/export, maybe add (gt) or similar to Menu item labels when in GT mode, to inform user they are in GT mode and that is what will be imported/exported etc

**Comment by roian** [comment]
it would be good to have some way to indicate that these trk files are gt labels, not regular labels.  at the very least, the _labels.trk suffix could become _gt_labels.trk.  for those of us heathens that use one long video with training labels and gt labels, the current form of export would have the effect of overwriting previously exported regular labels.  which would be unfortunate.

**Comment by allenleetc** [comment]
Labels exported when in GT mode (either table-form or trk-form) have new default name of _gtlabels.
Avail in feature/deeptrack
