### ISSUE TITLE
Function to automatically create APT projects

### ISSUE THREAD

**Issue by stephenhuston** [kristinbranson/APT#207]
A updated function to automatically create APT projects and import videos and .trk files would be useful for batch project creation.  I'm currently using CreateTestAPTProject.m (attached) but the projects it creates are starting to fall behind the current APT project structure.
[CreateTestAPTProject.txt](https://github.com/kristinbranson/APT/files/2054394/CreateTestAPTProject.txt)

**Comment by allenleetc** [comment]
Pushed util/createProject.m which is similar/related but not a drop-in replacement for CreateTestAPTProject. CreateTestAPTProject has some SHLab-specific behavior which is not present in createProject. eg:
* createProject accepts movFiles array with arbitrary number of views
* calibration files are optional; if supplied must be pre-computed for each movieset

**Comment by stephenhuston** [comment]
Works great for me.  Thank you!  Closing
