### ISSUE TITLE
bug: show predicted replicates

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#214]
doesn't work when you choose to store only final replicates in tracking menu options

**Comment by arobie** [comment]
forgot - you can't track any significant number of frames storing all iterations without running out of memory.

**Comment by arobie** [comment]
and if you're going to touch this code anyway - a shortcut to show/not show would be appreciated.

**Comment by allenleetc** [comment]
getting replicates to appear requires navigating one frame in the UI. This is true in a few places in APT, often changing one frame will refresh the UI.

changing title to the shortcut sub-issue.
