### ISSUE TITLE
Add option "Y" to timeline drop down menu

### ISSUE THREAD

**Issue by stephenhuston** [kristinbranson/APT#231]
The option "Y" and most of the "y_mean", "y_median" etc. options are not visible in the drop down menu for the timeline plot (Windows Matlab R2016b).

**Comment by stephenhuston** [comment]
y is missing from landmark_features.yaml

**Comment by kristinbranson** [comment]
Thanks for debugging this, fixed the problem by adding y to landmark_features.yaml.
