### ISSUE TITLE
gui nicety: timeline indicator for tracked or imported tracked frames? 

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#232]
Would be helpful to have visual indication of whether tracking or imported predictions exist for a given frame. Maybe background color of labels timeline could change? grey/black might not interfere with most color maps of labels, predictions, etc.

**Comment by arobie** [comment]
Ok - not sure how to deal with throughput, maybe an option to jump to incompletely labeled frames in navigation menu? but i agree that in the majority of cases target are fully labeled. 
But I do think a labeled, tracked or imported indicateor would be more generally useful.

**Comment by allenleetc** [comment]
pulldown selection of labeled, tracked, imported has been in for a long time.
