### ISSUE TITLE
error labeling in New Project

### ISSUE THREAD

**Issue by roian** [kristinbranson/APT#243]
Labeling in either Sequential or Template mode in a New Project, get the following error:
(in Sequential mode)
Reference to non-existent field 'xdata'.

Error in Labeler/prevAxesFreeze (line 10514)
       gd.image_prev.XData = freezeInfo.xdata;

Error in Labeler/InitializePrevAxesTemplate (line 10856)
         obj.prevAxesFreeze([]);

Error in LabelCoreSeq/acceptLabels (line 83)
     obj.labeler.InitializePrevAxesTemplate();

Error in LabelCoreSeq/hlpAxBDFLabelState (line 180)
       obj.acceptLabels();

Error in LabelCoreSeq/axBDF (line 100)
         obj.hlpAxBDFLabelState(false,tfShift);

Error in LabelCore>@(s,e)obj.axBDF(s,e) (line 157)
     set(obj.hAx,'ButtonDownFcn',@(s,e)obj.axBDF(s,e));

Error while evaluating Axes ButtonDownFcn. (edited)

=====================================
(similar message if try to label in Template mode, except the errors are in LabelCoreTemplate/acceptLabels etc)

**Comment by allenleetc** [comment]
believe this has been resolved
