### ISSUE TITLE
gui nicety: hide landmark numbers

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#246]
sometimes the landmark numbers are in the way when labeling. it would be nice to have the option to toggle off the numbers but not the label 'x's

**Comment by allenleetc** [comment]
You can now set the fontsize to like 0.1 which has the desired effect. The option to toggle the numbers off for predictions is available. The option to toggle the numbers off for labels is currently disabled for silly technical reasons, maybe the FontSize thing can work well enough.
