### ISSUE TITLE
trk output files

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#255]
auto generated name should include tracker type info

**Comment by allenleetc** [comment]
which auto-generated name, the <longtimestamp>_<longtimestamp2>.trk or some other? those names theoretically are not intended for public consumption although adding a little metadata never hurts.

**Comment by arobie** [comment]
right now it uses project name.trk, but projects can have more than 1 trained tracker now. so it would be good to automatically include which tracker type was used to make the trk being output. does apt just store all the predicting you've done regardless of what tracker did the predicting? in that case it could get super messy and maybe you don't want auto naming scheme

**Comment by arobie** [comment]
yes. trk exported by the GUI in anyway. 
glad to hear they are not mixed for exporting. i can try to double check. but i'm not good at finding my tracking in the ocean of NaNs.

**Comment by allenleetc** [comment]
results across trackers should not be mixed. we do have an outstanding/known issue about like if you retrain the same DL tracker, you may get mixed tracking results from diff tracker versions.

**Comment by allenleetc** [comment]
$trackertype macro is now added/available for trkfile export. It is included in the default trkfilename
