### ISSUE TITLE
tracking parameter descriptions need to be updated for theta alignment specification changes

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#262]
Head landmark and Tail landmark refer to arbitrary trx-specified which I think has been removed.

**Comment by allenleetc** [comment]
The head/tail still needs to be specified for "arbitrary" -- atm this guides CPR in determining/computing the orientation of an animal.

**Comment by allenleetc** [comment]
Closing this for now but please re-open if necessary.
