### ISSUE TITLE
switch targets doesn't work for MDN project

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#276]
Error using Labeler/trackGetBigLabeledTrackedTable (line 10006)
Unrecognized variable name 'mov'.

Error in Labeler/hlpTargetsTableUIgetBigTable (line 4538)
      tblBig = obj.trackGetBigLabeledTrackedTable('wbObj',wbObj);

Error in Labeler/targetsTableUI (line 4549)
      [tfok,tblBig] = obj.hlpTargetsTableUIgetBigTable();

Error in LabelerGUI>menu_go_targets_summary_Callback (line 3315)
handles.labelerObj.targetsTableUI();

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 33)
    gui_mainfcn(gui_State, varargin{:});

Error in LabelerGUI>@(hObject,eventdata)LabelerGUI('menu_go_targets_summary_Callback',hObject,eventdata,guidata(hObject)) (line 423)
  'Callback',@(hObject,eventdata)LabelerGUI('menu_go_targets_summary_Callback',hObject,eventdata,guidata(hObject)),...
 
Error while evaluating Menu Callback.

**Comment by allenleetc** [comment]
fixed with e0b410
