### ISSUE TITLE
Merging an existing deeplabcut project to APT

### ISSUE THREAD

**Issue by Yaraat92** [kristinbranson/APT#309]
Hi,

I wish to use the output given by APT  as input data for the JAABA classifier. I have previously used Deeplabcut for tracking of mouse body parts. That is, I have trained the program to track mouse ears and tail base. Can I use these existing training data to create a new APT project?
I am asking this because training the program took many hours of work, and I assume it would be the same with APT.. So I'm wondering whether there is a way to merge the data and not do it all from the beginning?

Thanks,
Yara.

**Comment by allenleetc** [comment]
Hi Yara,

Nice to meet you! We are planning on adding DLC import functionality into APT to support users who have existing DLC projects. 

To get things going quickly, it's probably easiest if we imported your existing movies and training labels into a new APT project, but then asked you to retrain your network. Would that work for you? As you may know, APT implements several deep networks for animal tracking with DLC being one of the available options. Training and tracking are designed to be painless through the fully-featured GUI.

If possible it would be great if you could share your project with me offline as a test case for our import code. Let us know, thanks!

**Comment by mkabra** [comment]
Hi Yara,

I've added a function createFromDeeplabcut to APT. Can you try it out?

Usage:
`APT.setpath;
createFromDeeplabcut('/path/to/dlc/traindir/info.csv')
`

**Comment by 2909ft** [comment]
I tried the function today and it worked :)
