### ISSUE TITLE
.lbl file no longer opens

### ISSUE THREAD

**Issue by BenHabermeyer** [kristinbranson/APT#335]
Hello, I updated my APT today to newest version (was previously using version from 1-2 weeks ago). The .lbl file of a pre-trained CPR tracker no longer loads in the GUI. When I select file->load project I get the following error message. It appears that the DLBackEnd class object cannot be loaded? I tried on the previous version I had and it opened just fine.

Here is the full MATLAB error message.

>> lObj = StartAPT;
Loading Java Customizations in UIExtrasTable.jar
Labeler GUI created.
Untarring project into C:\Users\Ben\Documents\.apt\tpe685bc43_c395_49c8_afc0_c414edb6e343
... done with untar.
Warning: Cannot load an object of class 'DLBackEnd':
Its class cannot be found. 
> In Labeler/projLoad (line 2098)
  In LabelerGUI>menu_file_load_Callback (line 2833)
  In gui_mainfcn (line 95)
  In LabelerGUI (line 48)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('menu_file_load_Callback',hObject,eventdata,guidata(hObject)) 
Index exceeds the number of array elements (1).

Error in Labeler.lblModernize (line 3197)
          assert(isequal(s.trackerClass(:),trkersInfo(1:nExistingTrkers)));

Error in Labeler/projLoad (line 2107)
      s = Labeler.lblModernize(s);

Error in LabelerGUI>menu_file_load_Callback (line 2833)
  currMovInfo = lObj.projLoad();

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('menu_file_load_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback.

**Comment by allenleetc** [comment]
Hey Ben,
That's strange, I can't reproduce this or see why this would occur yet. If you haven't tried this already, can you try killing your MATLAB, restarting, and trying to load your project again? MATLAB monitors your local filesystem and the object/class system can sometimes get confused if there are any changes.

Another debugging point, at any time after the 'StartAPT' command, running `which DLBackEnd` in MATLAB should return the m-file at \<APT\>/matlab/trackers/dt/DLBackEnd.m.

**Comment by BenHabermeyer** [comment]
seems like I cloned the repo and default branch is 'develop' which doesn't have the <APT>/matlab/trackers/dt directory
