### ISSUE TITLE
command line tracking

### ISSUE THREAD

**Issue by BenHabermeyer** [kristinbranson/APT#336]
Hello, I am trying to use the command line to track movie(s) after loading a .lbl project into the APT GUI following https://github.com/kristinbranson/APT/wiki/Tracking-Movies-(DL-algorithms). I am using a pretrained CPR model (though the docs says non-CPR...?)

in MATLAB, after running `lObj = StartAPT;` and loading in the .lbl file from file->load project, I run `lObj.tracker.track({video_path}, 'trkfiles', {trk_path}, 'trxfiles', {trx_path});` with paths to the video, trk outfile, and trx.mat file I would like to use. I receive warnings that 'trkfiles' and 'trxfiles' are unknown parameter names which are ignored, and get the following error: 

```
useParFor = 1
maxNumCompThreads = 4
usetrxOrientation = 1
Dot indexing is not supported for variables of this type.

Error in tblfldscontainsassert (line 3)
assert(all(ismember(flds(:),t.Properties.VariableNames(:))),...

Error in CPRLabelTracker/track (line 1794)
      tblfldscontainsassert(tblMFT,MFTable.FLDSID);
```

Is command-line tracking not allowed with a CPR model or is there an error I am making? If CPR is not allowed what do you suggest going forwards for deploying a tracker using the command line?

**Comment by allenleetc** [comment]
Hey Ben,

Yes that wiki applies only to Deep-Learning trackers. I will update the wiki to clarify, apologies for the confusion.

Command-line tracking is available for CPR but the syntax is different for historical reasons. There are a couple ways to go; are you wanting to track movies that are not contained within your project? Are you looking to track a very large number of movies?

Backing up, does a commandline or graphical interface work better for you for tracking? We recently reorganized the tracking menu in the GUI; it's not hooked up for CPR yet, but we can prioritize that if it is useful. Other users are doing production CPR tracking as well.

**Comment by BenHabermeyer** [comment]
Hello Allen,

I am looking to use a pre-trained tracker .lbl project to track new videos (so not videos the project was trained with). Ideally would like to use the command line to accomplish this (similar to JAABADetect, where .jab classifier can be called from command line given paths to required files). It is part of a larger classification pipeline for many behavior videos produced over several years. If you have any guidance on the syntax for CPR tracking from command line that would be helpful.

Thanks
Ben

**Comment by allenleetc** [comment]
OK, cool. Here is something to try:

```
APTCluster /path/to/project.lbl track /path/to/movie.avi /path/to/trx.mat rawtrkname /path/to/output.trk

# functional form
APTCluster('/path/to/project.lbl','track','/path/to/movie.avi','/path/to/trx.mat','rawtrkname','/path/to/output.trk')

# startframe/endframe spec
APTCluster /path/to/project.lbl track /path/to/movie.avi /path/to/trx.mat rawtrkname /path/to/output.trk startFrame 1 endFrame 100 
```

A few notes:
* This function name and syntax are a little wonky but it's a vestige of running production tracking on a cluster resource. It runs fine for me on my local machine.
* This only does one (movie,trx) at a time. There is a batch option if you have a textfile containing many movies, but this option doesn't currently support trxfiles. If this causes pain just let us know. 
* This call will open up the APT UI but it should go away afterwards.

Let me know if this gets you going and maybe I can add this for the wiki as it may evolve. Thanks,
Allen

**Comment by BenHabermeyer** [comment]
APTCluster call seemed to work just fine with a test video, our .lbl file, and a trx.mat file. Generated .trk file at least. I'll integrate it into our pipeline for more testing but seems promising for our application (generating trx, generating trk, and using JAABA classifier for many individual videos one at a time). Thanks for the help

**Comment by allenleetc** [comment]
Great! Let us know how it goes. I'll circle back in a bit for some API cleanup, wiki/doc etc.

**Comment by allenleetc** [comment]
@BenHabermeyer pushed a new syntax with a more reasonable name. Also, in your previous comment you mention needing to run StartAPT initially -- I am guessing this was only necessary to set up your APT paths (see below). Otherwise it shouldn't be necessary (?).

Example of new syntax below. You can specify multiple movies/trx via cell arrays (movies will be tracked serially); otherwise it's just a more reasonably-named wrapper for the APTCluster call. We have other batch-tracking modalities (for deep-learning etc) that we are consolidating under the new syntax.

```
% this sets up your APT path
APT.setpath 

movs = {'/path/to/mov1.avi' '/path/to/mov2.avi'}; % cellstr or string array OK
trxs = {'/path/to/trx1.mat' '/path/to/trx2.mat'};
trkfiles = {'/path/to/out1.trk' '/path/to/out2.trk'};
trackBatch('lblfile','/path/to/proj.lbl','net','cpr','movfiles',movs,'trxfiles',trxs,'trkfiles',trkfiles);

% Note the 'net', 'cpr' specification is required and other/DL nets are not yet supported

% With start/end frame specification
trackBatch('lblfile','/path/to/proj.lbl','net','cpr','movfiles',movs,'trxfiles',trxs,'trkfiles',trkfiles,'startFrame',1,'endFrame',100);
```

**Comment by BenHabermeyer** [comment]
Ok yes was likely that startAPT was only needed to set up the required paths. Thanks for the update on the new syntax! Will pass this along. And again thanks for your help.
