### ISSUE TITLE
Error adjusting contrast in multiview

### ISSUE THREAD

**Issue by stephenhuston** [kristinbranson/APT#339]
Hi,

When trying to adjust brightness/contrast of a single view within a mutliview project I get the following error.  This is a new APT project that  was initialized using settings copied from an older legacy APT project so it might be an old project structure issue.

Error:File: createWindowClipPanel.m Line: 374 Column: 14
Identifier 'scaleDisplayPanelWidth' is not a function or a shared variable. To share 'scaleDisplayPanelWidth' with nested function, initialize it in the current scope. For
more information, see Sharing Variables Between Parent and Nested Functions.

Error in imcontrast_kb>createHistogramPalette (line 217)
    createWindowClipPanel(hFigFlow, imgModel);

Error in imcontrast_kb (line 130)
    hHistFig = createHistogramPalette(imageHandle, imgModel);

Error in LabelerGUI>menu_view_adjustbrightness_Callback (line 3185)
  	hConstrast = imcontrast_kb(handles.axes_all(iAxRead));

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)LabelerGUI('menu_view_adjustbrightness_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

**Comment by allenleetc** [comment]
@stephenhuston I only got warnings in MATLAB 19a but maybe you are running something more recent? Pushed a fix please give it a try.

**Comment by stephenhuston** [comment]
It now works on R0219b.  Thank you!
