### ISSUE TITLE
APT landmarks in JAABA

### ISSUE THREAD

**Issue by gainbrew** [kristinbranson/APT#340]
Hello,

I wasn't sure if this should be posted here or in the JAABA Github.  I am attempting to train a classifier in JAABA using APT tracking data.  I ran into an issue where the dots that represent each APT landmark are only showing up for the 1st animal. I have 12 targets, and it does appear that JAABA is able to train on features generated from the landmarks for all animals, but I am not actually able to visualize the dots.  

Thanks,
Ben

**Comment by gainbrew** [comment]
To clarify, I can confirm that the .trk file called in this JAABA project contains tracking information for all targets.

**Comment by mkabra** [comment]
Hi Ben,

Right now, JAABA only shows the dots for the animal that is currently
selected in JAABA. Do the dots don't show up even when you switch animals?

Mayank

**Comment by gainbrew** [comment]
Hi Mayank,

That's correct.  When switching targets the dots don't appear and I still see them on the original animal.  

Thanks,
Ben

**Comment by mkabra** [comment]
I re-checked and actually the dots should be visible for all animals even
if they are not selected. I presume you did the usual step of restarting
Matlab and that also didn't fix it. Do you see any errors printed out in
the Matlab's Command Window when you load the project or switch animals? If
not, can you send me an example movie file, trx file, APT trk file, and the
JAABA project file? I don't think I need the APT project file but if I do
I'll ask for it.

Mayank

**Comment by gainbrew** [comment]
Sorry for the delay, our MATLAB license expired.  I didn't see anything printed in the command window when loading the project or when switching animals.  Below is a link for all requested files, let me know if anything further is needed.  Thanks! 

https://drive.google.com/file/d/1-VZGSEEngXFI3zvhS-ZyHkCggGTkDwzV/view?usp=sharing

**Comment by mkabra** [comment]
Ok yeah, there was a bug because of which the APT trk points were plotted
outside the frame. I've fixed the bug and pushed it to github. Try it out.

Mayank

**Comment by gainbrew** [comment]
That did the trick, thanks so much!
