### ISSUE TITLE
Total number of frames APT could track

### ISSUE THREAD

**Issue by Junes94** [kristinbranson/APT#342]
Hi,
I wonder the maximum number of frames APT could track.
I have a movie of 32000 frames. When I tried to track all of the frames, it failed. (I used 49c43c0 version of APT but the error doesn't seem the matter of version)
So, I gradually increased the number of frames to be tracked.
9400 frames succeeded, and 10000 frames failed. 
you could see the failure screenshot and logs below.
![trackingError10000frames](https://user-images.githubusercontent.com/64457340/94152748-e522fd80-feb6-11ea-8fb6-3e2c1a85bfa1.jpg)

```
### Job 1:
### C:\Users\MyPC\Documents\.apt\tp10db12ce_a279_4ac9_9f09_94daf50c05ac\xvid0\deeplabcut\view_0\20200921T160735\trk\raw1_trn20200921T160735_iter20000_20200924T223548_mov1_vwj1.err

2020-09-24 22:39:12,797 C:\Users\MyPC\Desktop\APT-49c43c082faf20b679bf99f64c3962b572723cae\deepnet\APT_interface.py classify_movie_all [ERROR] Could not track movie
Traceback (most recent call last):
  File "C:\Users\MyPC\Desktop\APT-49c43c082faf20b679bf99f64c3962b572723cae\deepnet\APT_interface.py", line 2060, in classify_movie_all
    classify_movie(conf, pred_fn, model_file=model_file, **kwargs)
  File "C:\Users\MyPC\Desktop\APT-49c43c082faf20b679bf99f64c3962b572723cae\deepnet\APT_interface.py", line 1996, in classify_movie
    write_trk(out_file + '.part', pred_locs, extra_dict, start_frame, to_do_list[cur_start][0], trx_ids, conf, info, mov_file)
  File "C:\Users\MyPC\Desktop\APT-49c43c082faf20b679bf99f64c3962b572723cae\deepnet\APT_interface.py", line 1876, in write_trk
    os.rename(out_file_tmp,out_file)
FileExistsError: [WinError 183] 파일이 이미 있으므로 만들 수 없습니다: 'C:\\Users\\MyPC\\Documents\\.apt\\tp10db12ce_a279_4ac9_9f09_94daf50c05ac\\xvid0\\deeplabcut\\view_0\\20200921T160735\\trk\\raw1_trn20200921T160735_iter20000_20200924T223548_mov1_vwj1.trk.part.tmp' -> 'C:\\Users\\MyPC\\Documents\\.apt\\tp10db12ce_a279_4ac9_9f09_94daf50c05ac\\xvid0\\deeplabcut\\view_0\\20200921T160735\\trk\\raw1_trn20200921T160735_iter20000_20200924T223548_mov1_vwj1.trk.part'
```

I could track all of my movie by tracking 4700 frames repeatedly.
I just wonder the limitation of frames to be tracked and if someone could fix it, it would be my pleasure.
Thank you.

**Comment by allenleetc** [comment]
Hey June,
No there should be no limitation on the number of frames to track. It might be best if I can test directly on your project -- it's possible it's a resource issue on your machine. If that sounds good can you direct message me at allenleetc - at - gmail? Thanks, Allen

**Comment by allenleetc** [comment]
Hey June, 
I pushed a fix for this, let me know if you still encounter any issues!
Thanks, Allen
