### ISSUE TITLE
tried to use track multiple movies GUI

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#344]
1. Please add default trk file macros. 
2. Tried to add a movie using GUI and kept getting this error 

Conversion to double from cell is not possible.

Error in TrackBatchGUI/setMovData (line 322)
        obj.toTrack.f0s(moviei,1) = {1};

Error in TrackBatchGUI/pb_add_Callback (line 389)
      obj.setMovData(moviei,movdataout);

Error in TrackBatchGUI>@(h,e)obj.pb_add_Callback(h,e) (line 224)
        'Callback',@(h,e) obj.pb_add_Callback(h,e));
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback.

Conversion to double from cell is not possible.

Error in TrackBatchGUI/setMovData (line 322)
        obj.toTrack.f0s(moviei,1) = {1};

Error in TrackBatchGUI/pb_add_Callback (line 389)
      obj.setMovData(moviei,movdataout);

Error in TrackBatchGUI>@(h,e)obj.pb_add_Callback(h,e) (line 224)
        'Callback',@(h,e) obj.pb_add_Callback(h,e));
 
Error using uiwait (line 81)
Error while evaluating UIControl Callback.

**Comment by allenleetc** [comment]
I fixed some bugs for the tracking, it is working for the workflows I tried if you want to give it a try.

I split out the macro sub-issue into a new issue #346.
