### ISSUE TITLE
off by 1 error in the perframe feature timeline?

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#347]
I think the perframe features time line lags the video by a frame.

**Comment by allenleetc** [comment]
What feature are you looking at, something like imported/dx?

For something like imported/x, it seemed right to me; for dx, the current convention seems to be that "the timeline value represents the forward diff eg the step necessary to reach the next/following frame". Does this agree with your observation?

**Comment by arobie** [comment]
Yes, you're correct dx looks exactly like you describe. 
Ok. I see, so a peak in velmag means a large movement between this frame and next, as opposed to a large movement to get to this position. 
I can work with that.
