### ISSUE TITLE
exporting/importing trakcing params - doesn't export skeleton

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#348]
When I use this to grab the params 
lObj.trackGetParams('all',true);

and then try to use this to import params 
 lObj.trackSetParams(baseprojparams,'all',true)

I get an error (and there's no skelstr in the struct that trackGetParams creates that I can find)
Brace indexing is not supported for variables of this type.
Error in Labeler/setExtraParams (line 10659)
          skel(i,:) = sscanf(skelstr{i},'%d %d');
Error in Labeler/trackSetParams (line 10082)
        sPrm = obj.setExtraParams(sPrm);

**Comment by arobie** [comment]
Still getting this error for params from a project with a defined skeleton under view -> edit skeleton. 
Is there another place it should be defined? 

Brace indexing is not supported for variables of this type.

Error in Labeler/setExtraParams (line 10765)
          skel(i,:) = sscanf(skelstr{i},'%d %d');

Error in Labeler/trackSetParams (line 10157)
        sPrm = obj.setExtraParams(sPrm);

**Comment by allenleetc** [comment]
I hopefully pushed a fix for this if you want to pull and try it out?

**Comment by arobie** [comment]
works for me! thanks
