### ISSUE TITLE
JRC nslots specification is not saved with project

### ISSUE THREAD

**Issue by allenleetc** [kristinbranson/APT#350]
This is currently a transient property on DeepTracker, update it to be saved.

Note, this prop probably still belongs on DeepTracker and not BackEnd as it could differ depending on the net etc.

**Comment by arobie** [comment]
Would be awesome if this gave me a usable error message!
But what did you see in the log that tipped you off to a memory problem?

**Comment by allenleetc** [comment]
Two things in the log, 
1. As Mayank says, "Keyboard Interrupt" usually indicates a hard force-crash caused by something external to the process, eg the cluster scheduler.
2. At the bottom, the "Total Requested Memory" is ~15MB which is the maximum/amount provided by a single compute slot.

**Comment by arobie** [comment]
trying now

**Comment by arobie** [comment]
cmdline voodoo  lObj.tracker.jrcnslots = 2; 
(just in case someone else runs into this)

**Comment by allenleetc** [comment]
This prop is now saved in the project. This prop/setting is per-tracker.
