### ISSUE TITLE
Failing to single animal projects in to MA

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/APT#351]
Eg project to test - /groups/branson/home/robiea/Projects_data/Labeler_APT/Nan_labelprojects_touchinglabels/multitarget_bubble_20200811.lbl

**Comment by allenleetc** [comment]
@mkabra I pushed a fix and was able to load a diff bub proj. Haven't tried your example yet but guessing prob working.

**Comment by allenleetc** [comment]
this should work now
