### ISSUE TITLE
Loading .lbl file from APT - DLC into JAABA - Reference to non-existent field 'labels'

### ISSUE THREAD

**Issue by harshk95** [kristinbranson/APT#366]
Hi, 
I have a DLC project that we imported into APT and want to run JAABA on. When I import the .lbl file into JAABA using 'Import from APT project'
> Reference to non-existent field 'labels'.
> Error in APTProject>initialize (line 246)
>   s = apt.labels{ndx};
> Error in APTProject>APTProject_OpeningFcn (line 171)
> handles = initialize(handles);
> Error in gui_mainfcn (line 220)
>     feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure),
>     varargin{:});
> Error in APTProject (line 40)
>     [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
> Error in ProjectSetup>uibuttongroup1_SelectionChangedFcn (line 1070)
> aptStruct = APTProject('lbl_file',lbl_file);
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> Error in ProjectSetup (line 42)
>     gui_mainfcn(gui_State, varargin{:});
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ProjectSetup('uibuttongroup1_SelectionChangedFcn',get(hObject,'SelectedObject'),eventdata,guidata(get(hObject,'SelectedObject'))) 
> Error using uiwait (line 81)
> Error while evaluating ButtonGroup SelectionChangedFcn.

Would appreciate any help 
Thanks!

**Comment by allenleetc** [comment]
Hey harshk, 
I saw you opened this issue in the JAABA repo so I will close this one. Thanks for the report!
Allen
