### ISSUE TITLE
Perframe Feature list

### ISSUE THREAD

**Issue by holfordt** [kristinbranson/APT#369]
Hello,

I am wondering if there is a list with descriptions of all the per frame (.mat) features APT automatically detects?  Some of them seem fairly intuitive, but I am not sure what others are actually measuring.  I have found a description of the trk file, and even a short list of features through JAABA, but I can't seem to locate information on the APT ones.

Thanks,
Tim

**Comment by arobie** [comment]
Maybe this is what you're looking for https://github.com/kristinbranson/APT/wiki/Using-APT-tracking-data-in-JAABA

**Comment by holfordt** [comment]
Hi,

Thanks, that is definitely helpful for some of them and allows me a better guess about others, but there are still many features that aren't accounted for.  Here is the list of the perframe features that were generated when we ran a test, for your reference.  I don't know if all of them will be relevant to things we are interested in, but there may be a lot of useful information in there.

Thanks again,
Tim

![perframe1](https://user-images.githubusercontent.com/88455390/135878993-9fbeee8d-6ffa-4794-bc81-3a48b4931d76.png)
![perframe2](https://user-images.githubusercontent.com/88455390/135879008-a7df438c-20cf-4a7d-827a-a1cb91c10e4b.png)

**Comment by mkabra** [comment]
Hi Tim,

These are JAABA's trajectory based features. You can find their details in
the supplementary text of the JAABA paper (
https://www.nature.com/articles/nmeth.2281#Sec16).

HTH,
Mayank

**Comment by holfordt** [comment]
Hi Mayank,

Ah that is perfect. Thank you so much! I really appreciate it.

-Tim
