### ISSUE TITLE
Center and rotate target flips the video

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/APT#399]
Rotating flips left and right landmarks. Creates a load of confusion.

**Comment by mkabra** [comment]
Fixed this. Earlier both xdir and ydir were being set to "normal", which is not correct. Because when axis is in  image mode, ydir is reversed.

**Comment by allenleetc** [comment]
Just FYI I have seen some subtleties with this in the past. Axes may have this notion of being in "3D"/rotated mode (eg when camroll or rotation are applied) vs being in "2D"/regular mode (eg when Reset/Full screen is pressed). This is tied to X/YDir as you note and can get wonky.
