### ISSUE TITLE
Track > Landmark Parameters ... errors unless a reference frame has been set 

### ISSUE THREAD

**Issue by arobie** [kristinbranson/APT#404]
Would be nice if this checked and told user to set a reference frame rather than just erroring out. 

Unable to perform assignment with 0 elements on the right-hand side.

Error in landmark_specs.parseLabelerState (line 107)
      s = lpos{iMov};

Error in landmark_specs/startupFcn (line 410)
      slbl = obj.parseLabelerState(obj.lObj);

Error in landmark_specs (line 75)
      obj.startupFcn(varargin{:});

Error in LabelerGUI>menu_track_edit_skeleton_Callback (line 5117)
landmark_specs('lObj',lObj);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in LabelerGUI (line 48)
    gui_mainfcn(gui_State, varargin{:});

Error in LabelerGUI>@(hObject,eventdata)LabelerGUI('menu_track_edit_skeleton_Callback',hObject,eventdata,guidata(hObject)) (line 464)
  'Callback',@(hObject,eventdata)LabelerGUI('menu_track_edit_skeleton_Callback',hObject,eventdata,guidata(hObject)));
 
Error while evaluating Menu Callback.

**Comment by allenleetc** [comment]
this should be fixed
