### ISSUE TITLE
legacy file detection in loadLbl.m no longer working

### ISSUE THREAD

**Issue by stephenhuston** [kristinbranson/APT#412]
Hi,

loadLbl.m used to detect old .lbl files that were not tarred and just load them in raw .mat format (code snippet from line 5 of loadLbl.m copied below).  This is no longer working in Matlab 2023a.  I'm guessing it is because the error identifier thrown when attempting to untar non-tarred files has changed i.e.  if strcmp(ME.identifier,'MATLAB:untar:invalidTarFile') no longer catches the error.

Thanks!

try
  fprintf('Untarring project into %s\n',tname);
  rawLblFile = fullfile(tname,'label_file.lbl');
  untar(lbl_file,tname);
  fprintf('... done with untar.\n');
catch ME
  if strcmp(ME.identifier,'MATLAB:untar:invalidTarFile')
    warningNoTrace('Label file %s is not bundled. Using it in raw (mat) format.',lbl_file);
    rawLblFile = lbl_file;
  else
    ME.rethrow();
  end
end

**Comment by adamltaylor** [comment]
This appears to be fixed in the latest respective commits to the develop and multianimal branches.  What branch/commit are you using?

**Comment by stephenhuston** [comment]
Thanks,

It is probably because I'm on a weird branch: stephen_working, latest
commit.

Stephen

**Comment by adamltaylor** [comment]
OK.  I'm sure you know this, but you might copy loadLbl.m from either of those branches into yours.  I'm going to close this issue, but feel free to reopen if you think this is premature.
