### ISSUE TITLE
Training stuck at preprocessing 

### ISSUE THREAD

**Issue by pmussp** [kristinbranson/APT#414]
Hi,

I'm trying to train APT using the dlc network, but the training window gets stuck on "Preprocessing" without throwing any errors. 

![Screenshot](https://github.com/kristinbranson/APT/assets/28634244/2b56e71b-2f04-4b14-9026-3953c0c2e9af)

A docker job is created, but it doesn't seem like the GPU is being used (running nvidia-smi shows that only 200 Mb is being used by MATLAB). However, the docker backend passes the APT test for GPU access.

These are the specs I'm using:

Ubuntu 20.04.6 LTS
MATLAB 2023b
NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER]
Driver Version: 550.54.15 
CUDA 11.8
APT main branch
Docker backend (latest)

I've attached the log file and the .lbl file. Any help debugging this issue would be greatly appreciated!

Best,
Peter

[20240625T155325view0_20240625T155325_tdptrx_new.log](https://github.com/user-attachments/files/15978376/20240625T155325view0_20240625T155325_tdptrx_new.log)
[lbl_file.zip](https://github.com/user-attachments/files/15978425/lbl_file.zip)

**Comment by mkabra** [comment]
Hi Peter,

Thanks for attaching the screenshot and the log file. I assume it has been stuck on preprocessing for more than 5-10 minutes. Can you reopen the project, start the training, let it run for an hour, then use "Bundle working directory" from the File menu and send me the tarball (or the zip file)? Looking at the log files, the training is running, but the monitor is probably not getting updated.

Mayank
________________________________
From: pmussp ***@***.***>
Sent: Wednesday, June 26, 2024 2:09 AM
To: kristinbranson/APT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kristinbranson/APT] Training stuck at preprocessing (Issue #414)

External Email: Use Caution



Hi,

I'm trying to train APT using the dlc network, but the training window gets stuck on "Preprocessing" without throwing any errors.

Screenshot.png (view on web)<https://urldefense.com/v3/__https://github.com/kristinbranson/APT/assets/28634244/2b56e71b-2f04-4b14-9026-3953c0c2e9af__;!!Eh6p8Q!DtrHJvGh7GgTAKaWx3vZ1x7-ziahiUb4KrJhPRgH_itVIYIHIeUMzpyLGpBt3n29T0BjR6cF8TVI54Pv6Jq4ZSy6kSU$>

A docker job is created, but it doesn't seem like the GPU is being used (running nvidia-smi shows that only 200 Mb is being used by MATLAB). However, the docker backend passes the APT test for GPU access.

These are the specs I'm using:

Ubuntu 20.04.6 LTS
MATLAB 2023b
NVIDIA Corporation TU104 [GeForce RTX 2070 SUPER]
Driver Version: 550.54.15
CUDA 11.8
APT main branch
Docker backend (latest)

I've attached the log file and the .lbl file. Any help debugging this issue would be greatly appreciated!

Best,
Peter

20240625T155325view0_20240625T155325_tdptrx_new.log<https://urldefense.com/v3/__https://github.com/user-attachments/files/15978376/20240625T155325view0_20240625T155325_tdptrx_new.log__;!!Eh6p8Q!DtrHJvGh7GgTAKaWx3vZ1x7-ziahiUb4KrJhPRgH_itVIYIHIeUMzpyLGpBt3n29T0BjR6cF8TVI54Pv6Jq4y7Bbtgo$>
lbl_file.zip<https://urldefense.com/v3/__https://github.com/user-attachments/files/15978425/lbl_file.zip__;!!Eh6p8Q!DtrHJvGh7GgTAKaWx3vZ1x7-ziahiUb4KrJhPRgH_itVIYIHIeUMzpyLGpBt3n29T0BjR6cF8TVI54Pv6Jq4qCBFxIE$>

**Comment by pmussp** [comment]
Hi Mayank,

Here is a zip file of the working directory after running for ~1 hour. 

[working_dir.zip](https://github.com/user-attachments/files/16015490/working_dir.zip)

**Comment by mkabra** [comment]
Ok yeah, it is not training at all. Can you send the movie used in the project (/mnt/data/peter_data/2024_05_24/experiment_01/experiment_01_20240524_084400_behavior_camera_video_undist.avi) and the git version of the APT you use so that I can recreate the issue?

Mayank
________________________________

**Comment by pmussp** [comment]
Hi Mayank,

I created a new APT project and was not able recreate the issue. I'm able to track videos without any errors now. I think the problem might have been somehow due to the project having been initially created using a different git branch (the develop branch) and then having switched to the main branch. Since this is probably not recommended, it might not be worth debugging the issue. 

Peter
