### ISSUE TITLE
"Clear" labels button does not update the labeledposMarked field

### ISSUE THREAD

**Issue by mkabra** [kristinbranson/APT#64]
If you label a frame, accept the labels, and later clear them using "Clear" button, then the labeledposMarked field has value "1". Although, labeledpos has "Nan"s when you clear the labels. Still, I think the labeledposMarked should have values "0" when user hits clear.

**Comment by allenleetc** [comment]
Maybe just remove markedness entirely now

**Comment by allenleetc** [comment]
marked-ness has been removed moving fwd
